project: 
  type: website
  output-dir: docs
  render:
    - "*.*"
    - "!topics-2025/2025-cefi/*"
    - "!topics-2025/2025-echopype/*"
    - "!topics-2025/2025-PACE/*"
    - "!topics-2025/2025-02-21-earthdata/gdalcubes.qmd"
    - "!topics-2025/2025-02-21-earthdata/zarr.qmd"

default-image-extension: ""
    
resources:
  - topics-2025/images
  - topics-2025/2025-02-21-earthdata/images
  - topics-2025/2025-02-28-ERDDAP-Py/images
  
execute:
  freeze: auto
  
website:
  page-navigation: true  
  title: "NMFS HackHours 2025"
  favicon: "images/favicon-16x16.png"
  site-url: https://nmfs-opensci.github.io/NMFSHackDays-2025
  repo-url: https://github.com/nmfs-opensci/NMFSHackDays-2025
  repo-actions: [edit, issue, source]
  
  page-footer: <img src="https://github.com/nmfs-opensci/assets/blob/main/logo/nmfs-opensci-logo2.png?raw=true" alt="NMFS Open Science logo" style="width:150px"><br />NMFS Open Science (2023)

  navbar:
    background: primary
    search: true
    right: 
      - icon: server
        href: https://nmfs-openscapes.2i2c.cloud/
        text: "JupyterHub"
      - icon: wechat
        href: https://github.com/orgs/nmfs-openscapes/discussions/categories/hackhours
        text: "Discussions"
      - icon: github
        href: https://github.com/nmfs-opensci/NMFSHackDays-2025
        text: "repo"
      - icon: globe
        href: https://github.com/nmfs-opensci
        text: "GH org"
  sidebar:
    - id: home
      logo: https://github.com/nmfs-opensci/assets/blob/main/logo/nmfs-opensci-logo2.png?raw=true
      style: "docked"
      collapse-level: 1
      toc-expand: false
      pinned: true
      align: left
      contents:
        - href: content/hackhours.md
          text: About
        - section: JupyterHub Skills
          href: topics-skills/index.md
          contents:
            - href: content/jhub.md
              text: About the Hub
            - href: content/setup.md
              text: Quick Start
            - text: Intro to JupyterHubs
              href: topics-skills/01-intro-to-jupyterhub.qmd
            - text: JupyterLab
              href: topics-skills/02-intro-to-lab.md
            - text: Intro to Git
              href: topics-skills/02-git.md
            - text: Git Authentication
              href: topics-skills/02-git-authentication.md
            - text: Git in JupyterLab
              href: topics-skills/02-git-jupyter.md
            - text: RStudio
              href: topics-skills/02-rstudio.qmd
            - text: Git in RStudio
              href: topics-skills/02-git-rstudio.md
            - text: Git in the terminal
              href: topics-skills/02-git-terminal.md
            - text: Other images
              href: topics-skills/04-other-images.md
            - text: Earthdata login
              href: topics-skills/03-earthdata.md
            - text: S3 Scratch Bucket
              href: topics-skills/03-ScratchBucket.ipynb
            - text: AWS S3 Bucket
              href: topics-skills/03-AWS_S3_bucket.ipynb
            - text: Learning resources
              href: topics-skills/04-learning.md
        - text: "HackHour 2025 Topics"
        - text: "---"
        - section: "Python - NASA Earth Data"
          href: topics-2025/2025-02-14-earthdata/index.html
          contents:
            - text: Earth Data catalog
              href: topics-2025/2025-02-14-earthdata/0-earthdata-catalog.html
            - text: earthaccess package
              href: topics-2025/2025-02-14-earthdata/1-earthaccess.html
            - text: Subset and plot
              href: topics-2025/2025-02-14-earthdata/2-subset-and-plot.html
            - text: Apply a polygon boundary
              href: topics-2025/2025-02-14-earthdata/3-polygon.html
            - text: Data cubes and aggregating
              href: topics-2025/2025-02-14-earthdata/4-data-cubes.html
        - section: "R - NASA Earth Data"
          href: topics-2025/2025-02-21-earthdata/index.html
          contents:
            - text: Earth Data catalog
              href: topics-2025/2025-02-21-earthdata/0-earthdata-catalog.html
            - text: earthaccess package
              href: topics-2025/2025-02-21-earthdata/1-earthdatalogin.html
            - text: Subset and plot
              href: topics-2025/2025-02-21-earthdata/2-subset-and-plot.html
            - text: Apply a polygon boundary
              href: topics-2025/2025-02-21-earthdata/3-polygon.html
            - text: Data cubes and aggregating
              href: topics-2025/2025-02-21-earthdata/4-data-cubes.html
        - section: "Python - ERDDAP"
          href: topics-2025/2025-02-28-ERDDAP-Py/index.html
          contents:
            - text: Match to points on a track
              href: topics-2025/2025-02-28-ERDDAP-Py/erddap_intro_satellite_matchup_track_2_options.html
            - text: Data cubes with ERDDAP and xarray
              href: topics-2025/2025-02-28-ERDDAP-Py/erddap_xarray.html
        - section: "R - ERDDAP"
          href: topics-2025/2025-03-07-ERDDAP-R/index.html
          contents:
            - text: Match to points on a track
              href: topics-2025/2025-03-07-ERDDAP-R/matchup_satellite_buoy_data.html
            - text: Masking shallow pixels
              href: topics-2025/2025-03-07-ERDDAP-R/mask-shallow-ocean-color.html
        - text: "---"
        - href: content/reuse.md
          text: Reuse Statement
        - href: coc.md
          text: Code of Conduct
format:
  html:
    theme:
      light: cosmo
      dark: [cosmo, theme-dark.scss]
    code-background: true
    code-copy: true
    css: styles.css
    toc: true
    toc-depth: 2
    include-before-body: translate.html

#filters:
#  - include-files.lua
#  - quarto
