---
title: ERDDAP in R
author: Sunny Hospital and Daisy Shi (CoastWatch)
---

Link to original repos in CoastWatch org: [CoastWatch tutorials R](https://github.com/coastwatch-training/Workshops/tree/main/NMFS-HackHour-Cloud-JupyterHubs/22March2024-R)

## Tutorials

* [Match up satellite to buoy data](matchup_satellite_buoy_data.html)
* [(Optional) Mask shallow pixels for satellite ocean color datasets](mask-shallow-ocean-color.html)

## Tutorials

## How to download and open the tutorials

### Jupyter Hub

1. Start the Jupyter Hub server <nmfs-openscapes.2i2c.cloud>
2. Click the orange Open in Jupyter Hub button

### Download 

1. Download to your local computer
2. You will need to have R (and RStudio/Positron) installed
3. Install any needed packages

### How to clone the git repository

This code is run in a terminal. After cloning, you will need to navigate to the tutorials in the `topics-2025` directory.

Never cloned the NMFSHackDays-2025 repo?

```
cd ~
git clone https://github.com/nmfs-opensci/NMFSHackDays-2025
```

Have cloned it but need to update? This is going to destroy any changes that you made to the repo to make it match the current state of the repo on GitHub.

```  
cd ~/NMFSHackDays-2025
git fetch origin
git reset --hard origin/main
```



